export const homeelements = {
  welcomename: ".content > span",
  jobsnavbar: ".nI-gNb-custom-Jobs > .nI-gNb-menuItems__anchorDropdown > div",
  companiesnavbar: ":nth-child(2) > .nI-gNb-menuItems__anchorDropdown > div",
  servicesnavbar: "[title='Naukri FastForward- Resume Services']",
  searchplaceholder: ".nI-gNb-sb__placeholder",
  searchkeytxt: '[placeholder="Enter keyword / designation / companies"]',
  searchexperiencedropdown: "#experienceDD",
  searchkeylocationtxt: "[placeholder='Enter location']",
  searchlookup: "button.nI-gNb-sb__icon-wrapper",
  searchexperiencedropdownlistparent: "#sa-dd-scrollexperienceDD",
  notificationicon: ".nI-gNb-nc__icon-wrapper > .ni-gnb-icn",
  profileicon: ".nI-gNb-icon-img",
  profilemenuicon: ".nI-gNb-drawer__bars",
  leftnavprofilepic: ".user-img",
  leftnavcompleteprofilebtn: ".button-wrapper",
  leftnavmyhome: ".highlighted > span",
  leftnavjobs: ".tabs-ul > :nth-child(2) > span",
  leftnavcompanies: ".tabs-ul > :nth-child(3) > span",
  leftnavblogs: ":nth-child(4) > span",
  recommendedjobs1:
    '[data-slide-index="0"] > .ni-citem-content > .tupleWrap > .cust-job-tuple',
  parentofallcomapany: ".tupleContainer",
  parentofalljobslist: ".styles_jlc__main__VdwtF",
  parentoffilter: "[class='styles_filterContainer__4aQaD']",
  parentofallfiltercheckbox: "[class='styles_filterOptns__1vq77']",
  parentofsinglejoblist: ".srp-jobtuple-wrapper",
  joblisttitle: "a.title",
  joblistlocation: ".locWdth",
  joblistexperience: ".expwdth",
  workModeRemotechkbox: "#chk-Remote-wfhType-",
  workmodehybridchkbox: "#chk-Hybrid-wfhType-",
  workmodetempwfhchkbox: `[id='chk-Temp. WFH due to covid-wfhType-']`,
  jobnavrecommendedjob: ".nI-gNb-dropdownMenuGroup > :nth-child(1) > a > div",
  jobnavjobfromrecruiter: ".nI-gNb-dropdownMenuGroup > :nth-child(1) > a > div",
  jobnavjobsfromalerts:
    ".nI-gNb-custom-Jobs > .nI-gNb-dropdown > .nI-gNb-dropdownMenuGroup > :nth-child(3) > a > div",
  jobnavapplicationstatus:
    ".nI-gNb-custom-Jobs > .nI-gNb-dropdown > .nI-gNb-dropdownMenuGroup > :nth-child(4) > a > :nth-child(1)",
  jobnavsavedjobs:
    ".nI-gNb-custom-Jobs > .nI-gNb-dropdown > .nI-gNb-dropdownMenuGroup > :nth-child(5) > a > div",
  recommendedjobtitle: ".reco-head-txt",
  savedjobpagelabel: ".countLabel",
  updateprofile: ".nI-gNb-info__sub-link",
  textresumelink:
    '[href="https://resume.naukri.com/resume-writing-services?fftid=101001"]',
  visualresumelink: '[title="Visual resume"]',
  resumecritiquelink: '[title="Resume critique"]',
  jonbsforulink: 'title="Jobs4u"',
  priorityapplicantlink:
    '[href="https://resume.naukri.com/priority-job-application?fftid=101019"]',
  contactuslinkservicenav: '[title="Contact us"]',
  resumedisplaylink: '[title="Resume display"]',
  jobsearchboosterlink: 'title="Job search booster"',
  basicandpremiumplanslink: '[title="Basic & premium plans"]',
  resumequalityscorelink: '[title="Resume quality score"]',
  resumesamplelink: '[title="Resume samples"]',
  joblettersamplelink: '[title="Job letter samples"]',
  resumemakingtitle: 'div[class="bluContntHd"]',
  aboutususernametxt: "#useremailId",
};
