export const login = {
  naukrilogo: ".fl",
  jobs: ":nth-child(1) > .nI-gNb-menuItems__anchorDropdown > div",
  companies: ":nth-child(2) > .nI-gNb-menuItems__anchorDropdown > div",
  services: ":nth-child(3) > .nI-gNb-menuItems__anchorDropdown > div",
  searchboxtxt: ".nI-gNb-sb__main",
  searchicon: ".nI-gNb-sb__icon-wrapper > .ni-gnb-icn",
  loginbtn: "#login_Layer",
  registerbtn: "#login_Layer",
  forEmployerdrpdown:
    ".nI-gNb-foremp > .nI-gNb-menuItems__anchorDropdown > :nth-child(1)",
  Loginlabel:
    ".nI-gNb-foremp > .nI-gNb-menuItems__anchorDropdown > :nth-child(1)",
  usernamelabel:
    ".nI-gNb-foremp > .nI-gNb-menuItems__anchorDropdown > :nth-child(1)",
  usernametxt: "#usernameField",
  passwordlabel: ":nth-child(2) > .input-field > .lbl",
  passwordtxt: "#passwordField",
  showpassword: ".fs13",
  forgotpassword: ".forgot-password-wrapper > .blue-text",
  loginsubmitbtn: ".blue-btn",
  useotp: ".otpButton",
  orlabel: ".ortext",
  googleicon: ".google-icon",
  googlesigninbtn: ".socialbtn",
  googlesiginlabel: ".socialbtn",
  newnaukrilabel: ".info-wrapper > :nth-child(1) > .col > .hdn",
  newnaukridesc1: ".info-list > :nth-child(1) > .col",
  newnaukridesc2: ".info-list > :nth-child(2) > .col",
  newnaukridesc3: ".info-list > :nth-child(3) > .col",
  newnaukridesc4: ".info-list > :nth-child(4) > .col",
  registerfreebtn: ".white-btn",
  illustrationimage: ".registerimage",
  invalidusererrorlabel: "#loginForm > :nth-child(2) > .col",
  usernameblnkerrorlabel: "#usernameField_err",
  passwordblankerrorlabel: "#passwordField_err",
};
