export const register={
        naukrilogo:'[href="https://www.naukri.com"] > img',
        login:'span > a',
        alreadyregisteredlabel:'.content > span',
        headingofregister:'.global-title-1',
        fullnamelabel:'.upload-Name > .formField > .resman-input > .labelClass',
        fullnametxt:'#name',
        fullnameerrorlabel:'.upload-Name > .formField > .resman-input > .__assitive > .__at',
        emaillabel:'.formElems > :nth-child(1) > .resman-input > .labelClass',
        emailtxt:'#email',
        emailerrorlabel:':nth-child(1) > .resman-input > .__assitive > .__at',
        passwordlabel:':nth-child(2) > .resman-input > .labelClass',
        passwordtxt:'#password',
        passworderrorlabel:':nth-child(2) > .resman-input > .__assitive > .__at',
        mobilelabel:'.mobileInput > .resman-input > .labelClass',
        mobilenumbertxt:'#mobile',
        mobileerrorlabel:'.mobileInput > .resman-input > .__assitive > .__at',
        workstatuslabel:'.userType > .resman-input > .labelClass',
        experiencedlabel:'[data-val="exp"] > .textWrap > .main-3',
        experiencepara:'[data-val="exp"] > .textWrap > .main-2',
        experienceicon:'[data-val="exp"] > .iconWrap > img',
        experiencestatusbtn:'[data-val="exp"]',
        fresherstatusbtn:'[data-val="fresher"]',
        fresherlabel:'[data-val="fresher"] > .textWrap > .main-3',
        fresherparalabel:'[data-val="fresher"] > .textWrap > .main-2',
        freshericon:'[data-val="fresher"] > .iconWrap > img',
        outsideindiacheckbox:'.ico',
        outsideindialabel:'.outsideIndiaWrapper > .checkbox-wrap > .chk-label',
        currentcitylabel:'.taxonomy-loc-suggestor > .labelClass',
        currentcitytxt:'#currentCity',
        outsidecityindiatxt:'.undefined',
        currentcityerrorlabel:'.taxonomy-loc-suggestor > .__assitive > .__at',
        currentcountrytxt:'#currentCountry',
        currentcountrylabel:'.countryWrap > .labelClass',
        currentcountryerrorlabel:'.countryWrap > .__assitive > .__at',
        uploadresumelabel:'.resume-upload-container > .labelClass',
        resumedescriptionlabel:'.info',
        uploadresumebtn:'.uploadResume',
        uploadresumefile:'.uploadAction',
        uploadresumeparent:'.resume-upload',
        uploadresumeerrorlabel:'div.info',
        notificationchkbox:'.ico-tick',
        notificationlabel:'.chk-label',
        privacylabel:'.confirmText',
        registerbtn:'.submitbtn',
        leftregisterimg:'.static-list',
        footer:'footer > div > p',
        googlesiginlabel:'.signupwith',
        googlesigninbtn:'.socialbtn',
        aboutus:'ul > :nth-child(1) > a',
        contactus:'ul > :nth-child(2) > a',
        faqs:':nth-child(3) > a',
        termsnconditionfooter:':nth-child(4) > a',
        reportfooter:':nth-child(5) > a',
        privacyfooter:'ul > :nth-child(6) > a'
}